In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/we_fn_use_c_marketing_customer_value_analysis.csv')

In [4]:
df.shape

(9134, 24)

In [3]:
df.sample(5)

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
5021,GO94903,Oregon,4770.550911,Yes,Basic,College,2/1/11,Medical Leave,F,12964,...,37,0,4,Personal Auto,Personal L3,Offer1,Web,362.774545,Two-Door Car,Medsize
2831,AK90865,Oregon,8207.858272,No,Basic,High School or Below,2/22/11,Unemployed,F,0,...,17,0,5,Special Auto,Special L2,Offer2,Agent,686.908270,Sports Car,Medsize
8067,WM36886,California,5757.442258,Yes,Basic,Master,1/31/11,Employed,M,88997,...,71,0,3,Corporate Auto,Corporate L2,Offer2,Branch,174.041566,Four-Door Car,Small
5774,ZF58696,California,13104.149110,No,Extended,High School or Below,2/7/11,Unemployed,M,0,...,31,0,2,Personal Auto,Personal L3,Offer1,Agent,1430.548077,Sports Car,Medsize
8580,EP64069,California,5138.244998,No,Basic,Bachelor,1/8/11,Employed,F,72264,...,66,0,9,Corporate Auto,Corporate L3,Offer3,Web,272.649844,Four-Door Car,Medsize

In [5]:
df.to_csv(r'D:\ironhack\data_tableau.csv', index=False)